name: Build all images

# todo: exclusive to current branch, but for now we're hackinng
on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        variants:
          - name: gnome
            includes: "live-iso,base-disk"

    uses: ./.github/workflows/katsu.yml
    with:
      arch: ${{ matrix.arch }}
      variant: ${{ matrix.variants.name }}
      include: ${{ matrix.variants.includes }}
